[supervisord]
pidfile=/tmp/supervisord-fried-rice.pid
nodaemon=false
logfile=%(here)s/logs/supervisord.log
logfile_maxbytes=1MB
logfile_backups=2
loglevel=info

[supervisorctl]
serverurl=unix:///tmp/supervisord-fried-rice.sock

[unix_http_server]
file=/tmp/supervisord-fried-rice.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[program:hugo]
command=hugo server --bind 127.0.0.1 --port 1314 --source %(here)s/../exampleSite
directory=%(here)s/..
stdout_logfile=%(here)s/logs/hugo.log
stderr_logfile=%(here)s/logs/hugo.err.log
stdout_logfile_maxbytes=5MB
stderr_logfile_maxbytes=5MB
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=5

[program:proxy]
command=caddy run --config %(here)s/Caddyfile
stdout_logfile=%(here)s/logs/proxy.log
stderr_logfile=%(here)s/logs/proxy.err.log
stdout_logfile_maxbytes=5MB
stderr_logfile_maxbytes=5MB
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=5
